# Generated by Django 5.2 on 2025-04-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cidade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
